random_seed: 42
dtype: 'float32'
datafile: 'datasets/Lorenz_10Kx10K.npy'
ntrain: 9700
nval: 100 
ntest: 200
npts: 10000
H: 100
input_size: 500
batch_size: 512
max_steps: 300000
val_check_steps: 5000
lr_schedule_params:
  lr: 1.e-4
  name: "ReduceLROnPlateau"
  gamma: 0.5
  patience: 1 
  threshold: 1.e-2
  min_lr: 1.e-7
loss: "MAE"
nhits_params:
  n_stacks: 4
  n_pool_kernel_size: [10,4,2,1]
  n_freq_downsample: [60,25,6,1]
  n_blocks: [1,1,1,1]
  mlp_units: [[4096,4096],[4096,4096],[4096,4096],[4096,4096]]
    #n_pool_kernel_size: [10,4,2,2,1]
    #n_freq_downsample: [60,25,6,2,1]
    #n_blocks: [1,1,1,1,1]
    #mlp_units: [[2048,2048],[2048,2048],[2048,2048],[2048,2048], [2048,2048]]


