name: mochaNN
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - numpy=1.21
  - pytorch
  - pytorch-cuda=12.1
  - lightning
  - ray-train
  - ray-tune
  - matplotlib=3.7
  - scipy
  - tqdm
